name: Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Frontend-Vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --legacy-peer-deps --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  Deploy-Backend-Render:
    runs-on: ubuntu-latest
    env: # <-- Make them available globally
      NODE_ENV: production
      MONGO_DB: ${{ secrets.MONGO_DB }}
      GENAI_API_KEY: ${{ secrets.GENAI_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_CHAT_MODEL: ${{ secrets.OPENAI_CHAT_MODEL }}
      OPENAI_EMBEDDING_MODEL: ${{ secrets.OPENAI_EMBEDDING_MODEL }}
      OLLAMA_CLOUD: ${{ secrets.OLLAMA_CLOUD }}
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
      OLLAMA_LOCAL_HOST: ${{ secrets.OLLAMA_LOCAL_HOST }}
      OLLAMA_CHAT_MODEL: ${{ secrets.OLLAMA_CHAT_MODEL }}
      OLLAMA_EMBEDDING_MODEL: ${{ secrets.OLLAMA_EMBEDDING_MODEL }}
      VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY }}
      VOYAGE_EMBEDDING_MODEL: ${{ secrets.VOYAGE_EMBEDDING_MODEL }}
      EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
      PORT: ${{ secrets.PORT }}
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
